### PR TITLE
Adding CI KBaseBiochem.spec

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
I'm not sure why we are adding in this file here. Is it for reference?

**Comment by samseaver** [comment]
I thought this had been merged. Yea we're making sure that the specs themselves have a place where we can run version-control on the workspace data types.

**Comment by samseaver** [comment]
I'd just made two more commits, but they are relatively innocuous, the compartment bug meant that only cytosolic reactions were being recognized as gapfilled reactions.

**Comment by samseaver** [comment]
I made the mistake of somehow overwriting/removing the original point of the PR

**Review by JamesJeffryes — APPROVED** [review]
Looks Good

**Pull request merged**
